collections:
  ansible.netcommon:
    version: 8.1.0
  ansible.posix:
    version: 2.1.0
  ansible.utils:
    version: 6.0.0
  arista.avd:
    version: 5.7.0
  arista.cvp:
    version: 3.12.0
  arista.eos:
    version: 12.0.0
  community.general:
    version: 11.3.0
