---
- name: Deploy to CloudVision
  hosts: all
  connection: local
  gather_facts: false

  tasks:

    - name: Deploy to Static Configuration Studio
      ansible.builtin.import_role:
        name: arista.avd.cv_deploy

