---
fabric_name: SITE1_FABRIC

# Set Design Type to L3L2 with EVPN VXLAN
design:
  type: l3ls-evpn

# Spine Switches
spine:
  defaults:
    platform: cEOS
    loopback_ipv4_pool: 10.250.1.0/24
    bgp_as: 65100
  nodes:
    - name: s1-spine1
      id: 1
      mgmt_ip: 192.168.0.10/24
    - name: s1-spine2
      id: 2
      mgmt_ip: 192.168.0.11/24

# Leaf Switches
l3leaf:
  defaults:
    platform: cEOS 
    spanning_tree_priority: 4096 
    spanning_tree_mode: mstp
    loopback_ipv4_pool: 10.250.1.0/24
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 10.255.1.0/24
    uplink_switches: [ s1-spine1, s1-spine2 ]
    uplink_interfaces: [ Ethernet51/1, Ethernet52/1 ]
    uplink_ipv4_pool: 172.16.1.0/24
    mlag_interfaces: [ Ethernet49/1, Ethernet50/1 ]
    mlag_peer_ipv4_pool: 10.251.1.0/24
    mlag_peer_l3_ipv4_pool: 10.252.1.0/24
    virtual_router_mac_address: 00:1c:73:00:00:99
  node_groups:
    - group: S1_RACK1
      bgp_as: 65101
      filter:
        tags: [ Infra ]
      nodes:
        - name: s1-leaf1
          id: 1
          mgmt_ip: 192.168.0.12/24
          uplink_switch_interfaces: [ Ethernet1/1, Ethernet1/1 ]
        - name: s1-leaf2
          id: 2
          mgmt_ip: 192.168.0.13/24
          uplink_switch_interfaces: [ Ethernet2/1, Ethernet2/1 ]
    - group: S1_RACK2
      bgp_as: 65102
      filter:
        tags: [ Infra ]
      nodes:
        - name: s1-leaf3
          id: 3
          mgmt_ip: 192.168.0.14/24
          uplink_switch_interfaces: [ Ethernet3/1, Ethernet3/1 ]
        - name: s1-leaf4
          id: 4
          mgmt_ip: 192.168.0.15/24
          uplink_switch_interfaces: [ Ethernet4/1, Ethernet4/1 ]
    - group: S1_BRDR
      bgp_as: 65103
      filter:
        tags: [ all ]
      evpn_gateway:
        evpn_l2:
          enabled: true
        evpn_l3:
          enabled: true
          inter_domain: true
      nodes:
        - name: s1-brdr1
          id: 5
          mgmt_ip: 192.168.0.100/24
          uplink_switch_interfaces: [ Ethernet31/1, Ethernet31/1 ]
          evpn_gateway:
            remote_peers: 
              - hostname: s2-brdr1
                bgp_as: 65203
                ip_address: 10.250.2.7
        - name: s1-brdr2
          id: 6
          mgmt_ip: 192.168.0.101/24
          uplink_switch_interfaces: [ Ethernet32/1, Ethernet32/1 ]
          evpn_gateway:
            remote_peers: 
              - hostname: s2-brdr2
                bgp_as: 65203
                ip_address: 10.250.2.8

l2leaf:
  defaults:
    platform: 7050SX3 
    spanning_tree_priority: 32768
    spanning_tree_mode: mstp
    mlag_interfaces: [ Ethernet49/1, Ethernet50/1 ]
    mlag_peer_ipv4_pool: 10.251.1.0/24
    mlag_peer_l3_ipv4_pool: 10.252.1.0/24
  node_groups:
    - group: S1_WIFI_GW
      filter:
        tags: [ "WIFI-GW-Transit", "S1-WIFI-USER" ]
      nodes:
        - name: s1-wifi-gw1
          id: 1
          mgmt_ip: 192.168.0.102/24
          uplink_switches: [ s1-brdr1, s1-brdr2 ]
          uplink_interfaces: [ Ethernet1, Ethernet2 ]
          uplink_switch_interfaces: [ Ethernet1, Ethernet1 ]
        - name: s1-wifi-gw2
          id: 2
          mgmt_ip: 192.168.0.103/24
          uplink_switches: [ s1-brdr1, s1-brdr2 ]
          uplink_interfaces: [ Ethernet1, Ethernet2 ]
          uplink_switch_interfaces: [ Ethernet2, Ethernet2 ]

generate_cv_tags:
  device_tags:
    - name: DC
      value: AVD-DEMO-SITE1
